# Generated by Django 4.2.29 on 2026-04-03 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=game.models.generate_room_code, max_length=6, unique=True)),
                ('board', models.JSONField(default=list)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('player_x', models.CharField(blank=True, max_length=100, null=True)),
                ('player_o', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('playing', 'Game in progress'), ('finished', 'Game finished')], default='waiting', max_length=10)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('game_mode', models.CharField(choices=[('multiplayer', 'Multiplayer'), ('ai_minimax', 'AI - Minimax'), ('ai_gemini', 'AI - Gemini')], default='multiplayer', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('join', 'Player Joined'), ('move', 'Move Made'), ('win', 'Game Won'), ('draw', 'Game Draw'), ('disconnect', 'Player Disconnected'), ('ai_move', 'AI Move')], max_length=15)),
                ('player', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.gameroom')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
